version: '3.1'

services:
  stats-server:
    ports:
      - "9090:9090"
    build: ./stat-service/stats-server
    depends_on:
      - stats-server-db
    container_name: stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-server-db:5432/stats-server-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-server-db:
    image: postgres:14-alpine
    container_name: stats-server-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-server-db:6542/ewm-service-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EWM_STATS_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root