version: '3.1'

services:
  stats-server:
    ports:
      - "9091:9091"
    build: ./stat-service/stats-server
    depends_on:
      - stats-server-db
    container_name: stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-server-db:5432/stats-server-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-server-db:
    image: postgres:14-alpine
    container_name: stats-server-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root